INSERT INTO public.companys (
	company_name, company_code, created_by)
VALUES
	('Company 1', 'COMP1', 'User1'),
    ('Company 2', 'COMP2', 'User2'),
    ('Company 3', 'COMP3', 'User3'),
    ('Company 4', 'COMP4', 'User4'),
    ('Company 5', 'COMP5', 'User5'),
    ('Company 6', 'COMP6', 'User6'),
    ('Company 7', 'COMP7', 'User7'),
    ('Company 8', 'COMP8', 'User8'),
    ('Company 9', 'COMP9', 'User9');

INSERT INTO public.usp_branchs (
    branch_code, branch_name, opening_date, range_ip, created_date, created_by, modified_date, modified_by, tvticketip, company_id
)
VALUES
    ('branch_code1', 'branch_name1', '2023-10-11', 10, CURRENT_TIMESTAMP, 'user1', null, null, null, 1),
    ('branch_code2', 'branch_name2', '2023-10-11', 20, CURRENT_TIMESTAMP, 'user2', null, null, null, 2),
	('branch_code3', 'branch_name3', '2023-10-11', 10, CURRENT_TIMESTAMP, 'user3', null, null, null, 1),
    ('branch_code4', 'branch_name4', '2023-10-11', 20, CURRENT_TIMESTAMP, 'user4', null, null, null, 2),
	('branch_code5', 'branch_name5', '2023-10-11', 10, CURRENT_TIMESTAMP, 'user5', null, null, null, 1),
    ('branch_code6', 'branch_name6', '2023-10-11', 20, CURRENT_TIMESTAMP, 'user6', null, null, null, 2),
	('branch_code7', 'branch_name7', '2023-10-11', 20, CURRENT_TIMESTAMP, 'user7', null, null, null, 2),
	('branch_code8', 'branch_name8', '2023-10-11', 10, CURRENT_TIMESTAMP, 'user8', null, null, null, 1),
    ('branch_code9', 'branch_name9', '2023-10-11', 20, CURRENT_TIMESTAMP, 'user9', null, null, null, 2);

INSERT INTO public.usp_configuration(
    paramname, value, created_date, created_by, modified_date, modified_by)
VALUES
    ('defaultpassword', 'Cana!@#123', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, NULL),
    ('autocall', 'yes', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, NULL),
    ('autocallafterwaited', 'yes', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, NULL),
    ('secondstoautocall', '3', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, NULL),
    ('secondsmaxwait', '480', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, NULL),
    ('secondsmaxserving', '480', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, NULL),
    ('secondsalertb4max', '30', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, NULL);


INSERT INTO usp_role (rolecode, rolename, created_date, created_by)
VALUES
  ('SADM', 'SuperAdmin', '2021-06-04 15:22:02.584747', 'admin'),
  ('ADM', 'Administrator', '2021-06-04 15:22:02.584747', 'admin'),
  ('ADM1', 'Admin1', '2021-06-04 15:22:02.584747', 'admin'),
  ('SPV', 'Supervisor', '2021-06-04 15:22:02.584747', 'admin'),
  ('CTR', 'Counter', '2021-06-04 15:22:02.584747', 'admin'),
  ('RPT', 'Reporter', '2021-06-04 15:22:02.584747', 'admin'),
  ('SUPHO', 'Supervisor HO', '2021-12-13 11:31:38.455362', 'k.seyha');	

INSERT INTO users (
	fullname, username, email, password, last_pwd_modified_date, phone_number, branch_id, status, roleid, counterno, created_date, created_by, modified_date, modified_by, description, deviceid)
VALUES
    ('risto nhen', 	'ristonhen','ristonhen@gmail.com', '$2y$10$EXqfcXx1558IpW9LCz5zM.vvrWQ.YRZapsKuhd.rw1oEuHpu8Gy3.', CURRENT_TIMESTAMP, NULL, 1, true, 1, NULL, CURRENT_TIMESTAMP, 'admin', NULL, NULL, NULL, NULL),
    ('Koa Seyha', 	'syhakoa','syhakoa@gmail.com', '$2y$10$EXqfcXx1558IpW9LCz5zM.vvrWQ.YRZapsKuhd.rw1oEuHpu8Gy3.', CURRENT_TIMESTAMP, NULL, 1, true, 1, NULL, CURRENT_TIMESTAMP, 'admin', NULL, NULL, NULL, NULL),
	('sokun Ouk', 	'sokunouk','sokunouk@gmail.com', '$2y$10$EXqfcXx1558IpW9LCz5zM.vvrWQ.YRZapsKuhd.rw1oEuHpu8Gy3.', CURRENT_TIMESTAMP, NULL, 1, true, 2, NULL, CURRENT_TIMESTAMP, 'admin', NULL, NULL, NULL, NULL),
    ('San Bunseang','sanbunseang', 'sanbunseang@gmail.com', '$2y$10$EXqfcXx1558IpW9LCz5zM.vvrWQ.YRZapsKuhd.rw1oEuHpu8Gy3.', CURRENT_TIMESTAMP, NULL, 2, true, 1, NULL, CURRENT_TIMESTAMP, 'admin', NULL, NULL, NULL, NULL),
	('Seang Sengty','seangsengty', 'seangsengty@gmail.com', '$2y$10$EXqfcXx1558IpW9LCz5zM.vvrWQ.YRZapsKuhd.rw1oEuHpu8Gy3.', CURRENT_TIMESTAMP, NULL, 2, true, 1, NULL, CURRENT_TIMESTAMP, 'admin', NULL, NULL, NULL, NULL),
    ('Muon Theret', 'muountheret','muountheret@gmail.com', '$2y$10$EXqfcXx1558IpW9LCz5zM.vvrWQ.YRZapsKuhd.rw1oEuHpu8Gy3.', CURRENT_TIMESTAMP, NULL, 2, true, 1, NULL, CURRENT_TIMESTAMP, 'admin', NULL, NULL, NULL, NULL),
    ('Sihado Som', 	'sihadosom','sihadosom@gmail.com', '$2y$10$EXqfcXx1558IpW9LCz5zM.vvrWQ.YRZapsKuhd.rw1oEuHpu8Gy3.', CURRENT_TIMESTAMP, NULL, 1, true, 1, NULL, CURRENT_TIMESTAMP, 'admin', NULL, NULL, NULL, NULL);
   
drop table usp_role;
drop table usp_rule_npms_assign;						
drop table votes;
drop table posts;
drop table menu_permission;
drop table users;
drop table usp_branchs;
-- Insert data to table menu
INSERT INTO menu_permission ("pms_menu_name","pms_menu_level","pms_parent_id","to_name","pms_menu_type","pms_menu_index","pms_menu_image","created_date","created_by","modified_date","modified_by","db_id")
	VALUES	('Dashboard',1,NULL,'dashboard',1,1,'mdi-view-dashboard',current_timestamp,'admin',NULL,'admin',NULL            ),
			('User & Permission',1,NULL,'userandpermission',1,2,'mdi-account-cog-outline',current_timestamp,'admin',NULL,NULL,NULL    ),
			('Administrator Tools',1,NULL,'administratortool',1,3,'mdi-cogs',current_timestamp,'admin',NULL,NULL,NULL     ),
			('Configuration',1,NULL,'configuration',1,4,'mdi-cog-transfer',current_timestamp,'admin',NULL,NULL,NULL                ),
			('Report',1,NULL,'report',1,5,'mdi-chart-areaspline',current_timestamp,'admin',NULL,NULL,NULL                         ),
			('Create User',2,2,'usermanagement',1,1,'fa-circle',current_timestamp,'admin',NULL,NULL,NULL                  ),
			('Change Password',1,NULL,'changepwd',2,1,'fa-edit',current_timestamp,'admin',NULL,NULL,NULL                  ),
			('Reset Password',2,2,'resetpwd',1,3,'mdi-circle-outline',current_timestamp,'admin',NULL,NULL,NULL                     ),
			('Create Role',2,2,'createrole',1,4,'mdi-circle-outline',current_timestamp,'admin',NULL,NULL,NULL                     ),
			('Role Permission',2,2,'rolePermission',1,5,'fa-circle',current_timestamp,'admin',NULL,NULL,NULL            ),
			('Exchange Rate',2,3,'exchange_rate',1,1,'mdi-account-multiple-outline',current_timestamp,'admin',NULL,NULL,NULL                ),
			('Counter',1,NULL,'queuecounter',1,6,'fa-users',current_timestamp,'admin',NULL,NULL,NULL                     ),
			('Create Branch',2,3,'createBranch',1,4,'mdi-circle-outline',current_timestamp,'admin',NULL,'m.tharet',NULL          ),
			('Create Service',2,3,'createService',1,5,'mdi-circle-outline',current_timestamp,'admin',NULL,'m.tharet',NULL        ),
			('Branch Service',2,3,'branchService',1,6,'mdi-circle-outline',current_timestamp,'admin',NULL,'m.tharet',NULL        ),
			('Counter Service',2,3,'counter_service',1,7,'fa-circle',current_timestamp,'admin',NULL,'m.tharet',NULL      ),
			('Menu Setting',1,NULL,'Menusetting',2,2,'fa-wrench',current_timestamp,'admin',NULL,NULL,NULL               ),
			('Queue Report',2,5,'queueReport',1,1,'fa-circle',current_timestamp,'admin',NULL,NULL,NULL                  ),
			('Counter Report',2,5,'counter_report',1,2,'fa-circle',current_timestamp,'admin',NULL,NULL,NULL              ),
			('Import Video',2,3,'importvideo',1,9,'fa-circle',current_timestamp,'admin',NULL,'m.tharet',NULL             ),
			('Online Counter',2,3,'online_counter',1,2,'fa-circle',current_timestamp,'m.tharet',NULL,'m.tharet',NULL     ),
			('NodeJS Logs',2,3,'nodejslog',1,10,'fa-circle',current_timestamp,'m.tharet',NULL,'m.tharet',NULL            ),
			('Online Ticket & TV',2,3,'online_ticket_tv',1,3,'mdi-circle-outline',current_timestamp,'m.tharet',NULL,'m.tharet',NULL),
			('User Report',2,5,'user_report',1,3,'fa-circle',current_timestamp,'m.tharet',NULL,NULL,NULL                 ),
			('Queue Monitoring',2,3,'queue_monitoring',1,8,'mdi-circle-outline',current_timestamp,'admin',NULL,'m.tharet',NULL    ),
			('Performance Report',2,5,'branch_performance',1,4,'fa-circle',current_timestamp,'admin',NULL,'m.tharet',NULL),
			('Free Counter',2,3,'free_counter',1,1,'mdi-circle-outline',current_timestamp,'m.tharet',NULL,NULL,NULL               ),
			('Database Setting',1,NULL,'dbsetting',2,3,'fa-solid fa-database',current_timestamp,'admin',NULL,'s.bunseang',NULL),
			('Test MIS Report',2,5,'mis_report',1,5,'fa-circle',current_timestamp,'s.bunseang',NULL,'s.bunseang',4       ),
			('Pre-Order Report',2,5,'pre_order_report',1,6,'fa-circle',current_timestamp,'s.bunseang',NULL,'s.bunseang',0),
			('Team',1,NULL,'team',1,1,'mdi-microsoft-teams',current_timestamp,'admin',NULL,'admin',NULL            ),
			('level1',1,NULL,'level1',1,1,'test',current_timestamp,'admin',NULL,'admin',NULL            ),
			('level2',2,32,'level2',1,2,'mdi-account-cog-outline',current_timestamp,'admin',NULL,NULL,NULL    ),
			('level3',3,33,'level3',1,2,'mdi-account-cog-outline',current_timestamp,'admin',NULL,NULL,NULL    ),
			('level4',4,34,'level4',1,2,'mdi-account-cog-outline',current_timestamp,'admin',NULL,NULL,NULL    );
			
			
INSERT INTO usp_rule_npms_assign ("roleid", "pmsid", "p_view", "p_view_data", "p_refresh", "p_search", "p_add", "p_edit", "p_delete", "p_save", "p_print", "p_import", "p_export", "created_date", "created_by", "modified_date", "modified_by")
	VALUES 	(1,1,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),			
			(1,2,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,3,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,4,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,5,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,6,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,7,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,8,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,9,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,10,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,11,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,12,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(1,13,True,True,True,True,True,True,False,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,14,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,15,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,16,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,17,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,18,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,19,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,20,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,21,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(1,22,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(1,23,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(1,24,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(1,25,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(1,26,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'s.bunseang',NULL,'NULL'),
			(1,27,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(1,29,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'s.bunseang',NULL,'NULL'),
			(1,30,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'s.bunseang',NULL,'NULL'),
			(2,1,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'admin'),
			(2,2,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,3,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'admin'),
			(2,4,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,5,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'admin'),
			(2,6,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,7,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'admin'),
			(2,8,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,9,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin' ),
			(2,10,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,11,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,12,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,13,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,14,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,15,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,16,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'admin'           ),
			(2,17,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(2,18,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'admin'           ),
			(2,19,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'admin'           ),
			(2,20,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'admin'),
			(3,1,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'            ),
			(3,2,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL' ),
			(3,3,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL' ),
			(3,4,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL' ),
			(3,5,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL' ),
			(3,6,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL' ),
			(3,7,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'            ),
			(3,8,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL' ),
			(3,9,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL' ),
			(3,10,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,11,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,12,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'           ),
			(3,13,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,14,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,15,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,16,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,17,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,18,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,19,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,20,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(3,21,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,22,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,23,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,24,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,25,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,26,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,27,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,29,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(3,30,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'NULL',NULL,NULL),
			(4,1,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'m.tharet'            ),
			(4,2,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet' ),
			(4,3,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet' ),
			(4,4,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet' ),
			(4,5,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'m.tharet'            ),
			(4,6,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet' ),
			(4,7,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL),
			(4,8,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet' ),
			(4,9,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet' ),
			(4,10,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,11,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,12,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,13,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,14,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,15,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,16,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,17,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL),
			(4,18,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,19,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'m.tharet'),
			(4,20,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,'m.tharet'   ),
			(4,21,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL ),
			(4,22,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL ),
			(4,23,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL ),
			(4,24,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL ),
			(4,25,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL ),
			(4,26,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,NULL            ),
			(4,27,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'m.tharet',NULL,NULL ),
			(5,1,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'             ),
			(5,2,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha'  ),
			(5,3,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'             ),
			(5,4,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha'  ),
			(5,5,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'             ),
			(5,6,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha'  ),
			(5,7,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'            ),
			(5,8,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha'  ),
			(5,9,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha'  ),
			(5,10,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha' ),
			(5,11,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha' ),
			(5,12,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha'),
			(5,13,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha' ),
			(5,14,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha' ),
			(5,15,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha' ),
			(5,16,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'            ),
			(5,17,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha'),
			(5,18,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'            ),
			(5,19,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'            ),
			(5,20,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,'k.seyha' ),
			(5,21,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,'k.seyha'            ),
			(5,22,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,NULL),
			(5,23,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,NULL),
			(5,24,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'k.seyha',NULL,NULL),
			(5,25,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'k.seyha',NULL,NULL),
			(1,32,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,33,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,34,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(1,35,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,1,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),			
			(7,2,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,3,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,4,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,5,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,6,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,7,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,8,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,9,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,10,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,11,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,12,False,False,False,False,False,False,False,False,False,False,False,current_timestamp,'admin',NULL,'NULL'),
			(7,13,True,True,True,True,True,True,False,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,14,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,15,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,16,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,17,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,18,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,19,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,20,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'admin',NULL,'NULL'),
			(7,21,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(7,22,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(7,23,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(7,24,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(7,25,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(7,26,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'s.bunseang',NULL,'NULL'),
			(7,27,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'m.tharet',NULL,'NULL'),
			(7,29,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'s.bunseang',NULL,'NULL'),
			(7,30,True,True,True,True,True,True,True,True,True,True,True,current_timestamp,'s.bunseang',NULL,'NULL');
			
update usp_rule_npms_assign set modified_by=NULL;


			
			
			